version: '3.8'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: denisbelikov/foodgram_backend
    env_file: .env
    volumes:
      - static:/app/collected_static
      - media:/app/media
    command: >
      sh -c "python wait_for_db.py &&
        python manage.py makemigrations recipes user &&
        python manage.py migrate &&
        gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db
    restart: always

  frontend:
    image: denisbelikov/foodgram_frontend
    env_file: .env
    command: sh -c "cp -r /app/build/. /frontend_static/ && sleep infinity"
    volumes:
      - static:/frontend_static/
    restart: always

  gateway:
    image: denisbelikov/foodgram_gateway
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - static:/staticfiles/
      - media:/media
      - ./nginx-gateway.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    restart: always
