version: '3.8'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    environment:
      POSTGRES_DB: foodgram
      POSTGRES_USER: foodgram_user
      POSTGRES_PASSWORD: your_strong_password
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: denisbelikov/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/backend_media
    command: >
      sh -c "./wait_for_db.sh &&
        python manage.py migrate &&
        gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db
    restart: always

  frontend:
    image: denisbelikov/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
    restart: always

  gateway:
    image: denisbelikov/foodgram_gateway
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - static:/staticfiles/
      - media:/media
      - ./nginx-gateway.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    restart: always
